import { SHAPE_CANDIDATES, Shape, ShapeContext } from '~/shapes.js'

export const piiImpact = (context: ShapeContext, shape: Shape) => {
  return impactLevelMap[context][shape]
}

// Impact levels are based on NIST SP 800-122 and FIPS 199
// More info here: https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf
// and here https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.199.pdf
export type PiiImpactLevel = 'LOW' | 'MODERATE' | 'HIGH'

const createImpactLevelMap = (
  level: PiiImpactLevel
): Record<string, PiiImpactLevel> => {
  const impactLevelMapEntry: Record<string, PiiImpactLevel> = {}
  for (const shape of Object.keys(SHAPE_CANDIDATES)) {
    impactLevelMapEntry[shape] = level
  }
  return impactLevelMapEntry
}

// We use a map of maps to allow for different impact levels for different contexts and shapes
// For example, a person's address is considered high impact in the PERSON context, but low impact in the GENERAL context
export const impactLevelMap: Record<
  ShapeContext,
  Record<Shape, PiiImpactLevel>
> = {
  PERSON: {
    UUID: 'LOW',
    INDEX: 'LOW',
    NUMBER: 'MODERATE',
    FULL_NAME: 'HIGH',
    FIRST_NAME: 'HIGH',
    LAST_NAME: 'HIGH',
    DESCRIPTION: 'LOW',
    DATE: 'LOW',
    DATE_OF_BIRTH: 'HIGH',
    GENDER: 'LOW',
    STREET_ADDRESS: 'HIGH',
    FULL_ADDRESS: 'HIGH',
    CITY: 'LOW',
    COUNTRY: 'LOW',
    STATE: 'LOW',
    ZIP_CODE: 'MODERATE',
    COUNTRY_CODE: 'LOW',
    LATITUDE: 'MODERATE',
    LONGITUDE: 'MODERATE',
    TIMEZONE: 'LOW',
    PHONE: 'HIGH',
    EMAIL: 'HIGH',
    PASSWORD: 'HIGH',
    USERNAME: 'MODERATE',
    TOKEN: 'HIGH',
    USER_AGENT: 'MODERATE',
    IP_ADDRESS: 'HIGH',
    MAC_ADDRESS: 'HIGH',
    LOGS: 'MODERATE',
    STATUS: 'LOW',
    EMPLOYER_IDENTIFICATION_NUMBER: 'HIGH',
    AGE: 'LOW',
    BANK_ACCOUNT_NUMBER_FULL: 'HIGH',
    BANK_ACCOUNT_NUMBER_LAST4: 'HIGH',
    BANK_ROUTING_FULL: 'HIGH',
    BANK_ROUTING_LAST4: 'HIGH',
    CHECKSUM: 'MODERATE',
    CREDIT_DEBIT_NUMBER: 'HIGH',
    CREDIT_DEBIT_EXPIRY: 'HIGH',
    CREDIT_DEBIT_CVV: 'HIGH',
    CURRENCY: 'LOW',
    DRIVER_ID: 'HIGH',
    HASH: 'MODERATE',
    LICENSE_PLATE: 'HIGH',
    META_DATA: 'HIGH', // Related to a person might contain personal information
    NATIONAL_IDENTIFICATION_NUMBER: 'HIGH',
    OTHER_NAME: 'MODERATE', // might be a middle nam'e
    PIN: 'HIGH',
    SEARCH_VECTOR: 'LOW',
    SSN_FULL: 'HIGH',
    SSN_LAST4: 'HIGH',
    SWIFT_CODE: 'HIGH',
    LOCATION: 'HIGH',
    TAX_CODE: 'HIGH',
    TAX_AMOUNT: 'MODERATE',
    TAX_IDENTIFICATION_NUMBER: 'HIGH',
    URL: 'LOW',
    VEHICLE_IDENTIFICATION_NUMBER: 'HIGH',
  },
  AUTHENTICATION: createImpactLevelMap('HIGH'), // Authentication impact can always be high
  FINANCE: {
    UUID: 'LOW',
    INDEX: 'LOW',
    NUMBER: 'MODERATE',
    FULL_NAME: 'HIGH',
    FIRST_NAME: 'HIGH',
    LAST_NAME: 'HIGH',
    DESCRIPTION: 'LOW',
    DATE: 'HIGH', // In finance, dates are often used for financial transactions
    DATE_OF_BIRTH: 'HIGH',
    GENDER: 'LOW',
    STREET_ADDRESS: 'HIGH',
    FULL_ADDRESS: 'HIGH',
    CITY: 'LOW',
    COUNTRY: 'LOW',
    STATE: 'LOW',
    ZIP_CODE: 'MODERATE',
    COUNTRY_CODE: 'LOW',
    LATITUDE: 'MODERATE',
    LONGITUDE: 'MODERATE',
    TIMEZONE: 'LOW',
    PHONE: 'HIGH',
    EMAIL: 'HIGH',
    PASSWORD: 'HIGH',
    USERNAME: 'MODERATE',
    TOKEN: 'HIGH',
    USER_AGENT: 'MODERATE',
    IP_ADDRESS: 'HIGH',
    MAC_ADDRESS: 'HIGH',
    LOGS: 'HIGH', // In finance, logs might contain financial transaction information
    STATUS: 'HIGH', // More important in finance
    EMPLOYER_IDENTIFICATION_NUMBER: 'HIGH',
    AGE: 'LOW',
    BANK_ACCOUNT_NUMBER_FULL: 'HIGH',
    BANK_ACCOUNT_NUMBER_LAST4: 'HIGH',
    BANK_ROUTING_FULL: 'HIGH',
    BANK_ROUTING_LAST4: 'HIGH',
    CHECKSUM: 'MODERATE',
    CREDIT_DEBIT_NUMBER: 'HIGH',
    CREDIT_DEBIT_EXPIRY: 'HIGH',
    CREDIT_DEBIT_CVV: 'HIGH',
    CURRENCY: 'LOW',
    DRIVER_ID: 'HIGH',
    HASH: 'MODERATE',
    LICENSE_PLATE: 'HIGH',
    META_DATA: 'HIGH', // In finance, metadata might contain financial transaction information or other sensitive information
    NATIONAL_IDENTIFICATION_NUMBER: 'HIGH',
    OTHER_NAME: 'LOW',
    PIN: 'HIGH',
    SEARCH_VECTOR: 'LOW',
    SSN_FULL: 'HIGH',
    SSN_LAST4: 'HIGH',
    SWIFT_CODE: 'HIGH',
    LOCATION: 'MODERATE', // In finance less important that in person
    TAX_CODE: 'HIGH',
    TAX_AMOUNT: 'MODERATE',
    TAX_IDENTIFICATION_NUMBER: 'HIGH',
    URL: 'LOW',
    VEHICLE_IDENTIFICATION_NUMBER: 'HIGH',
  },
  HEALTH: {
    UUID: 'LOW',
    INDEX: 'LOW',
    NUMBER: 'MODERATE',
    FULL_NAME: 'HIGH',
    FIRST_NAME: 'HIGH',
    LAST_NAME: 'HIGH',
    DESCRIPTION: 'LOW',
    DATE: 'LOW', // Likely wont have a substantial impact
    DATE_OF_BIRTH: 'HIGH',
    GENDER: 'LOW',
    STREET_ADDRESS: 'HIGH',
    FULL_ADDRESS: 'HIGH',
    CITY: 'LOW',
    COUNTRY: 'LOW',
    STATE: 'LOW',
    ZIP_CODE: 'MODERATE',
    COUNTRY_CODE: 'LOW',
    LATITUDE: 'MODERATE',
    LONGITUDE: 'MODERATE',
    TIMEZONE: 'LOW',
    PHONE: 'HIGH',
    EMAIL: 'HIGH',
    PASSWORD: 'HIGH',
    USERNAME: 'MODERATE',
    TOKEN: 'HIGH',
    USER_AGENT: 'MODERATE',
    IP_ADDRESS: 'HIGH',
    MAC_ADDRESS: 'HIGH',
    LOGS: 'HIGH', // In health, logs might contain personal information
    STATUS: 'HIGH', // In health, status might be sensitive
    EMPLOYER_IDENTIFICATION_NUMBER: 'HIGH',
    AGE: 'LOW',
    BANK_ACCOUNT_NUMBER_FULL: 'HIGH',
    BANK_ACCOUNT_NUMBER_LAST4: 'HIGH',
    BANK_ROUTING_FULL: 'HIGH',
    BANK_ROUTING_LAST4: 'HIGH',
    CHECKSUM: 'MODERATE',
    CREDIT_DEBIT_NUMBER: 'HIGH',
    CREDIT_DEBIT_EXPIRY: 'HIGH',
    CREDIT_DEBIT_CVV: 'HIGH',
    CURRENCY: 'LOW',
    DRIVER_ID: 'HIGH',
    HASH: 'MODERATE',
    LICENSE_PLATE: 'HIGH',
    META_DATA: 'HIGH', // In health, metadata might contain personal information
    NATIONAL_IDENTIFICATION_NUMBER: 'HIGH',
    OTHER_NAME: 'LOW',
    PIN: 'HIGH',
    SEARCH_VECTOR: 'LOW',
    SSN_FULL: 'HIGH',
    SSN_LAST4: 'HIGH',
    SWIFT_CODE: 'HIGH',
    LOCATION: 'MODERATE',
    TAX_CODE: 'HIGH',
    TAX_AMOUNT: 'MODERATE',
    TAX_IDENTIFICATION_NUMBER: 'HIGH',
    URL: 'LOW',
    VEHICLE_IDENTIFICATION_NUMBER: 'HIGH',
  },
  LEGAL: {
    UUID: 'LOW',
    INDEX: 'LOW',
    NUMBER: 'MODERATE',
    FULL_NAME: 'HIGH',
    FIRST_NAME: 'HIGH',
    LAST_NAME: 'HIGH',
    DESCRIPTION: 'LOW',
    DATE: 'LOW',
    DATE_OF_BIRTH: 'HIGH',
    GENDER: 'LOW',
    STREET_ADDRESS: 'HIGH',
    FULL_ADDRESS: 'HIGH',
    CITY: 'LOW',
    COUNTRY: 'LOW',
    STATE: 'LOW',
    ZIP_CODE: 'MODERATE',
    COUNTRY_CODE: 'LOW',
    LATITUDE: 'MODERATE',
    LONGITUDE: 'MODERATE',
    TIMEZONE: 'LOW',
    PHONE: 'HIGH',
    EMAIL: 'HIGH',
    PASSWORD: 'HIGH',
    USERNAME: 'MODERATE',
    TOKEN: 'HIGH',
    USER_AGENT: 'MODERATE',
    IP_ADDRESS: 'HIGH',
    MAC_ADDRESS: 'HIGH',
    LOGS: 'HIGH', // In legal, logs might contain personal information
    STATUS: 'HIGH', // In legal, status might be sensitive
    EMPLOYER_IDENTIFICATION_NUMBER: 'HIGH',
    AGE: 'LOW',
    BANK_ACCOUNT_NUMBER_FULL: 'HIGH',
    BANK_ACCOUNT_NUMBER_LAST4: 'HIGH',
    BANK_ROUTING_FULL: 'HIGH',
    BANK_ROUTING_LAST4: 'HIGH',
    CHECKSUM: 'MODERATE',
    CREDIT_DEBIT_NUMBER: 'HIGH',
    CREDIT_DEBIT_EXPIRY: 'HIGH',
    CREDIT_DEBIT_CVV: 'HIGH',
    CURRENCY: 'LOW',
    DRIVER_ID: 'HIGH',
    HASH: 'MODERATE',
    LICENSE_PLATE: 'HIGH',
    META_DATA: 'HIGH', // In legal, metadata might be sensitive
    NATIONAL_IDENTIFICATION_NUMBER: 'HIGH',
    OTHER_NAME: 'MODERATE', // might be a middle name
    PIN: 'HIGH',
    SEARCH_VECTOR: 'LOW',
    SSN_FULL: 'HIGH',
    SSN_LAST4: 'HIGH',
    SWIFT_CODE: 'HIGH',
    LOCATION: 'HIGH',
    TAX_CODE: 'HIGH',
    TAX_AMOUNT: 'MODERATE',
    TAX_IDENTIFICATION_NUMBER: 'HIGH',
    URL: 'LOW',
    VEHICLE_IDENTIFICATION_NUMBER: 'HIGH',
  },
  GENERAL: {
    UUID: 'LOW',
    INDEX: 'LOW',
    NUMBER: 'LOW',
    FULL_NAME: 'HIGH',
    FIRST_NAME: 'HIGH',
    LAST_NAME: 'HIGH',
    DESCRIPTION: 'LOW',
    DATE: 'LOW',
    DATE_OF_BIRTH: 'HIGH',
    GENDER: 'LOW',
    STREET_ADDRESS: 'LOW',
    FULL_ADDRESS: 'LOW',
    CITY: 'LOW',
    COUNTRY: 'LOW',
    STATE: 'LOW',
    ZIP_CODE: 'MODERATE',
    COUNTRY_CODE: 'LOW',
    LATITUDE: 'MODERATE',
    LONGITUDE: 'MODERATE',
    TIMEZONE: 'LOW',
    PHONE: 'HIGH',
    EMAIL: 'HIGH',
    PASSWORD: 'HIGH',
    USERNAME: 'MODERATE',
    TOKEN: 'HIGH',
    USER_AGENT: 'MODERATE',
    IP_ADDRESS: 'HIGH',
    MAC_ADDRESS: 'HIGH',
    LOGS: 'LOW', // Since logs arent related to person, finance or legal, they are likely low impact
    STATUS: 'LOW',
    EMPLOYER_IDENTIFICATION_NUMBER: 'HIGH',
    AGE: 'LOW',
    BANK_ACCOUNT_NUMBER_FULL: 'HIGH',
    BANK_ACCOUNT_NUMBER_LAST4: 'HIGH',
    BANK_ROUTING_FULL: 'HIGH',
    BANK_ROUTING_LAST4: 'HIGH',
    CHECKSUM: 'MODERATE',
    CREDIT_DEBIT_NUMBER: 'HIGH',
    CREDIT_DEBIT_EXPIRY: 'HIGH',
    CREDIT_DEBIT_CVV: 'HIGH',
    CURRENCY: 'LOW',
    DRIVER_ID: 'HIGH',
    HASH: 'MODERATE',
    LICENSE_PLATE: 'HIGH',
    META_DATA: 'LOW', // Since meta data is not related to person, finance or legal, it is likely low impact
    NATIONAL_IDENTIFICATION_NUMBER: 'HIGH',
    OTHER_NAME: 'LOW',
    PIN: 'HIGH',
    SEARCH_VECTOR: 'LOW',
    SSN_FULL: 'HIGH',
    SSN_LAST4: 'HIGH',
    SWIFT_CODE: 'HIGH',
    LOCATION: 'LOW', // Since location is not related to person, finance or legal, it is likely low impact
    TAX_CODE: 'HIGH',
    TAX_AMOUNT: 'MODERATE',
    TAX_IDENTIFICATION_NUMBER: 'HIGH',
    URL: 'LOW',
    VEHICLE_IDENTIFICATION_NUMBER: 'HIGH',
  },
}
